site_name: PowerCLIExamples
repo_url: https://github.com/jpsider/PowerCLIExamples
theme: readthedocs
pages:
- Home: index.md
- PowerCLIExamples Basics:
  - What is PowerCLIExamples: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
